apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-mock-deployment
  labels:
    app: ui-mock-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui-mock-deployment
  template:
    metadata:
      labels:
        app: ui-mock-deployment
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui
        env:
          - name: SWAGGER_JSON_URL
            value: "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json"
        ports:
        - containerPort: 8080
        name: openapi-mock
        image: muonsoft/openapi-mock
        env:
          - name: OPENAPI_MOCK_SPECIFICATION_URL
            value: "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json"
        ports:
        - containerPort: 8080
