---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ui-route
  namespace: api-first
spec:
  host: ui-api-first.apps.ocp4-test.itmlabs.io
  to:
    kind: Service
    name: ui-svc
  port:
    targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mock-route
  namespace: api-first
spec:
  host: mock-api-first.apps.ocp4-test.itmlabs.io
  to:
    kind: Service
    name: mock-svc
  port:
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  namespace: api-first
spec:
  selector:
    app: ui-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mock-svc
  namespace: api-first
spec:
  selector:
    app: mock-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-deployment
  labels:
    app: mock-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-deployment
  template:
    metadata:
      labels:
        app: mock-deployment
    spec:
      containers:
      - name: openapi-mock
        image: muonsoft/openapi-mock
        env:
          - name: OPENAPI_MOCK_SPECIFICATION_URL
            value: "https://raw.githubusercontent.com/erickeliseo/openapi/main/oas3demo.json"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-deployment
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui
        env:
          - name: SWAGGER_JSON_URL
            value: "https://raw.githubusercontent.com/erickeliseo/openapi/main/oas3demo.json"
        ports:
        - containerPort: 8080
---
